package com.hotel.hotel_booking.model;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Booking {

    private Long id;

    @NotBlank(message = "Guest name must not be empty!")
    private String guestName;

    @Pattern( regexp = "SingleRoom|DoubleRoom|Suite",
              message = "Room type must be Single, Double room or Suite")
    private String roomType;

    @Min(value =1, message="Number of guests must be at least 1")
    @Max(value = 3, message="Number of guests cannot exceed 3")
    private int numberOfGuests;

    private Double totalPrice;

    //CheckIN och CheckOUT— dates as plain strings (yyyy-MM-dd), no database needed
    @NotBlank(message = "Check-in date must not be empty!")
    private String checkIn;

    @NotBlank(message = "Check-out date must not be empty!")
    private String checkOut;

    //@Bean validation=@NotBlank ,@Pattern,@Min / @Max
    //@Data= generates also constructors automatically!
    //getters-setters already been generated by @Data. I do not need to apply again.
}
